title: SigneT Class Owners Association (UK)
email: secretary@sailsignet.org.uk
description: >- # this means to ignore newlines until "baseurl:"
  The SigneT is a 12’4” traditional racing dinghy designed in 1961 by the late Ian Proctor. In Ian’s own words, “the design problem set by the Sunday Times was to provide really good sailing and racing at the lowest possible cost” and over 50 years later the SigneT does exactly that.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: SailSigneT

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
